name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths: 
      - 'Dockerfile.base_llvm'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.base_llvm --tag rose

    - name: Push the Docker image
      run: |
        echo ${{ secrets.DOCKERHUB }} | docker login -u ouankou --password-stdin
        docker tag rose ouankou/rose:llvm
        docker push ouankou/rose:llvm
