name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.clang-mini --tag clang

    - name: Push the Docker image
      if: ${{ matrix.os }} == 'ubuntu-latest'
      run: |
        echo ${{ secrets.DOCKERHUB }} | docker login -u ${{ secrets.DOCKERHUB_ID }} --password-stdin
        docker tag clang ouankou/rose:clang10-mini
        docker push ouankou/rose:clang10-mini
