name: Docker Image ROSE Develop Weekly

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the docker image of ROSE develop branch
      run: |
        cd $GITHUB_WORKSPACE/freecc
        docker build . --file Dockerfile.rose-develop --tag freecc_rose_develop
        echo ${{ secrets.DOCKERHUB }} | docker login -u ${{ secrets.DOCKERHUB_ID }} --password-stdin
        docker tag freecc_rose_develop freecompilercamp/pwc:rose-develop-weekly
        docker push freecompilercamp/pwc:rose-develop-weekly

